language: node_js
node_js:
- '0.11'
before_script:
- npm install -g gulp
script:
- gulp
deploy:
  provider: heroku
  api_key:
    secure: cfQ03qqOoEsqKwLhO7qqslEHv9miwApSoR+AfJaBHK4oEdFjswlGNfLd2XHIa8jj78wZNaQrXg+uaxZQL4DtL6uq7DDJBwYGjTztDhBywODcdEshdWSngPKJwqN8gcq10D2N4UM9/mdhY7gfTArnWx0Wn+GRFrh3ZXr0rr/N7hbd1vG2qJq0csTenep/MMf0SFRJREYZwqEBevHGLFwEi0tMF8LSFOdp7cxhYBhtGQOZmhMxS3o77hcveOCfomizWWRtd+xSO92z6KIJjenqcJwdYkthloLeZ0f7GhHHUoQa9XG4VX3V7RprAtUw6ZgYQyoc8r4S8lFzN8nL/0Z+26orKNSJulbsRf6+bJJHPkQkdEF5zs/MB0vxDcfr5yWQO1IPWd/AgARsquNDKilLkqM75dmKS9/jyTiNt1DO+Glsxryk0lnMVPfVvdV9jLZstQLrv518dDjWMFowajDQDoOfq8f/Fv4EzjPDpm5/B77ALton7QHnlvgn3LIdDRzjYO6LyRES61JPJTCuYYD4wlQvydb3TuTQZG+2IrFzEzyLSdRA6b2LeQB4HrT9pmkYUKr+YdC46Naak4EbrxXvqO7kJUInZQSikU+ZSxmf6QyCD+psjMPVbDGoWSSdSXw4bblwiMmf+XI33TMraXkRSnCD9CvuvEuc0Q7zTJ5qn+o=
  app: open-telemetry
  on:
    repo: andysterland/open-telemetry
